# Configuration for qTagGer
# For Primer3 settings change the file "settings.bak"

# General Settings:
jobname: NeoChrIII
top: 5
target: "neochr_URA3.gb"

# Paths:
home: /home/qTagGer/qTagGer
primer3_path: /home/qTagGer/qTagGer/primer3/src/primer3_core
bowtie_path: /home/qTagGer/qTagGer/bowtie/index

# Primer Settings:
offtarget_size_cutoff: 10_000 # cutoff offtarget amplicon size
sponge_value: 5               # number of maximal offtarget binding sites across loci 
